# User model
FIRST_NAME_LENGTH = 150
LAST_NAME_LENGTH = 150
USERNAME_LENGTH = 150
EMAIL_LENGTH = 254
PASSWORD_LENGTH = 8

# Recipe model
TAG_NAME_LENGTH = 64
TAG_SLUG_LENGTH = 256
RECIPE_NAME_LENGTH = 256
INGREDIENT_NAME_LENGTH = 256
MEASUREMENT_UNITS_LENGTH = 256
MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1

# Pagination
PAGINATION_PER_PAGE = 6
